### ISSUE TITLE
can you share the source code of  'august-2016-grails-angular-scaffolding', the ‘myblog’

### ISSUE THREAD

**Issue by marsdonne** [jameskleeh/g32016-scaffolding#1]
hi,
i am a newbie to use Grails Angular Scaffolding Plugin， i got an error(null) when execute ‘ngGenerateAll domainClassName’， i guess the reason is 'embedded data' in my domain,  but, i see your article in https://objectcomputing.com/resources/publications/sett/august-2016-grails-angular-scaffolding,  you using 'embedded data' too,  so, can you share the source code, i want to learn， thanks

**Comment by jameskleeh** [comment]
Angular 1 - https://github.com/grails-plugins/grails-angularjs-scaffolding
Angular 2+ - https://github.com/grails-plugins/grails-angular-scaffolding
